name: CI

on:
  push:
    branches: ["*", "!main"]
  pull_request:
    branches: [main]

jobs:
  # lint: 必要になったら追加

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      - name: Install frontend dependencies 
        run: cd frontend && npm install
      - name: frontend test
        run: cd frontend && npm test
      - name: Install backend dependencies
        run: cd backend-ts && npm install
      - name: backend test
        run: cd backend-ts && npm test

  pre-merge-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository   
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
    
    - name: Install dependencies
      run: cd frontend && npm install
    - name: Build the project
      run: cd frontend && npm run build